misc

diff --git a/cgi/gpio b/cgi/gpio
--- a/cgi/gpio
+++ b/cgi/gpio
@@ -1,52 +1,66 @@
-#!/bin/bash -u
+#!/bin/bash 
+source ${0%/*}/cgi.inc
 
-# Manipulate GPIOs. Usage:
-#
-#  curl -f "http://pion/gpio?NN=op[...&NN=op]"
-#
-# Where NN is a GPIO number 2 to 27, and "op" can be:
-#
-#   0       - set the GPIO to an output and make it low
-#   1       - set the GPIO to output and make it high
-#   input   - set the GPIO to input and return "NN=0" or "NN=1"
-#
-# Multiple GPIOs are processed in order specified. An error will cause the
-# script to abort with some gpios already processed. 
+usage="/
+Usage:
+    
+    gpio [options]
+    -or-
+    curl -f http://pion/gpio[?option[&option...]]
 
-source cgi.inc
+Options are:
+    
+    G=0       - set gpio G to output low
+    G=1       - set gpio G to output high
+    G=in      - set gpio G to an input
+    G=disable - disable gpio G
+    disable   - disable all gpios
 
-die() { echo $* >&2; exit 1; }
+Where G is the gpio number 2 to 27. After options are processed (if any), list
+the current state of all enabled gpios.  
+"
+
+shopt -s nullglob nocasematch
 
 sys=/sys/class/gpio
 [ -d $sys ] || die "User-mode GPIOs not supported"
+
+# return list of enabled gpios
+enabled()
+{
+    for f in $sys/gpio[0-9]*; do echo ${f#$sys/gpio}; done | sort -n
+}
 
 # set gpio $1 direction to $2, or die
 direction() 
 { 
     [ -d $sys/gpio$1 ] || echo $1 > $sys/export
-    greq -q $2 $sys/gpio$1/direction || echo $2 > $sys/gpio$1/direction || die "Can't set gpio$gpio direction"
+    grep -q $2 $sys/gpio$1/direction || echo $2 > $sys/gpio$1/direction
 }
 
-(($#)) || die "Nothing to do!"
+for opt in "$@"; do
 
-printf "Content-type: text/plain\n\n"
-
-for query in "$@"; do
-    [[ $query =~ ^([0-9]+)=(.*) ]] || die "Invalid query '$query'"
+    if [[ $opt == di* ]]; then
+        for g in $(enabled); do
+          echo $g > $sys/unexport
+        done
+        continue
+    fi    
+    
+    [[ $opt =~ ^([0-9]+)=(.+) ]] || die "Invalid option '$opt'"
 
     gpio=${BASH_REMATCH[1]}
     op=${BASH_REMATCH[2]}
 
     case "$op" in
-        0|1)
-            direction $1 out
-            echo $op > $sys/gpio$1/value || die "Can't set gpio$gpio to $op"
-            ;;
-        
-        in*) 
-            direction $1 in
-            v=$(cat $sys/gpio/gpio$1/value)|| die "Can't get gpio$gpio value"
-            echo "$gpio=$value"
-            ;;
+        0|1) direction $gpio out; echo $op > $sys/gpio$gpio/value;;
+        in*) direction $gpio in;;
+        di*) [ -d $sys/gpio$gpio ] && echo $gpio > $sys/unexport;;
+        *) die "Invalid option '$opt'";;
     esac
 done
+
+shopt -s nullglob
+gpios=$(enabled)
+[[ $gpios ]] || die "No gpios enabled"
+for g in $gpios; do echo $g: $(cat $sys/gpio$g/direction $sys/gpio$g/value); done    
diff --git a/cgi/mkfm b/cgi/mkfm
--- a/cgi/mkfm
+++ b/cgi/mkfm
@@ -1,25 +1,36 @@
 #!/bin/bash -ue
 
-# curl http://172.31.255.1/cgi/mkfm?XXX.X[&timeout]
+source ${0%/*}/cgi.inc
 
-die() { echo "$*" >&1; exit 1; }
-
-source cgi.inc
-
-printf "Content-type: text/plain\n\n"
+usage="/
+Usage:
+    mkfm [options]
+    -or-
+    curl http://172.31.255.1/cgi/mkfm[?options&options...]
+Options are:
+    mhz=XXX.X - transmit frequency in MHz, 88.1 to 107.9, default is 99.9
+    tone=X    - modulation frequency in Hz, 10-8000, default is 1000
+    time=X    - transmit time in seconds, 0-120, default is 30. 0 just kills the current transmission. 
+"
 
 runfor=../runfor/runfor; [ -x $runfor ] || die "Need executable $runfor"
 sox=$(type -P sox) || die "Need executable sox"
 xmit=../FM_Transmitter_RPi3/fm_transmitter; [ -x $xmit ] || die "Need executable $xmit"
 
-freq=${1:-99.9}
-timeout=${2:-30}
+freq=99.9
+tone=1000
+time=30
 
-echo $freq | awk '{exit !(match($1,/^[0-9]+(.[0-9])?$/) && $1 >= 88.1 && $1 <= 107.9)}' || die "Invalid frequency '$frequency'"
-echo $timeout | awk '{exit $1 < 5 || $1 > 60}' || die "Invalid timeout '$timeout'"
+(($#)) && for a in "$@"; do case $a in
+    freq=*) freq=${a#*=}; echo $freq | awk '{exit !(match($1,/^[0-9]+(.[0-9])?$/) && $1 >= 88.1 && $1 <= 107.9)}' || die "Invalid frequency '$freq'";;
+    tone=*) tone=${a#*=}; echo $tone | awk '{exit !(match($1,/^[0-9]+$/) && $1 >= 10 && $1 <= 8000)}' || die "Invalid tone '$tone'";;
+    time=*) time=${a#*=}; echo $time | awk '{exit !(match($1,/^[0-9]+$/) && $1 >= 0 && $1 <= 120)}' || die "Invalid time '$tone'";;
+    *) die "$usage"
+esac; done    
 
-exec 2>&1
 pkill -f $xmit || true
-echo "Transmitting $freq MHz for $timeout seconds"
-# background from subshell or cgiserver will stall
-( $runfor $timeout bash -c "$sox -n -r22050 -c1 -b16 -t wav - synth 0 sine 1000 | $xmit -f $freq -" & ) &>/dev/null
+if ((time)); then
+    echo "Transmitting $tone Hz on $freq MHz for $time seconds"
+    # background from subshell or cgiserver will stall
+    ( $runfor $time bash -c "$sox -n -r22050 -c1 -b16 -t wav - synth 0 sine $tone | $xmit -f $freq -" & ) &>/dev/null
+fi  
